### ISSUE TITLE
Releases / docs

### ISSUE THREAD

**Issue by F0Xde** [Twister915/mcproto-rs#2]
Just wondering if there will be any releases published to [crates.io](https://crates.io), which would also have the added benefit of documentation being automatically available at [docs.rs](https://docs.rs).

This question of course also applies to `mctokio`

**Comment by Twister915** [comment]
Released on crates.io with a different implementation for `mctokio` called `craftio-rs`

See: https://crates.io/crates/mcproto-rs and https://crates.io/crates/craftio-rs

**Comment by F0Xde** [comment]
Great, thank you very much!
